version: '3.8'
services:
  app:
    container_name: myfirst_dockerized_rest_server
    build:  
      dockerfile: rest_api/Dockerfile
      context: .
    volumes:
      - ./rest_api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: myfirst_dockerized_database_server
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: "elozelo2137"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "world"
    ports:
      - "3306:3306"
    volumes:
      - ./db_dumps/world.sql:/docker-entrypoint-initdb.d/world.sql
